cleanall:
	-$(RM) $(CC_DEPS)$(C++_DEPS)$(OBJS)$(C_UPPER_DEPS)$(CXX_DEPS)
	-$(RM) $(SECONDARY_FLASH)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_UPPER_DEPS)$(C_DEPS)$(CPP_DEPS)
	-$(RM) *.elf *.bin *.map
	-$(RM) "${SDK_ROOT}/tools/SBOOT/image/"*ueboot.bin
	-$(RM) "${SDK_ROOT}/tools/SBOOT/public/"*ueboot*.img
	-@echo ' '